import Foundation

struct StringScoreTestCase: CustomStringConvertible
{
    var text: String!
    var searchString: String!
    var fuzziness: Double?
    var expectedScore: Double!

    var description: String {
        let fuzzinessString = fuzziness == nil ? "nil" : "\(fuzziness!)"
        return "Searching \"\(searchString)\" in \"\(text)\" with fuzziness \(fuzzinessString)"
    }
}

class StringScoreTestCaseManager
{
    class func defaultTestCaseArray() -> [StringScoreTestCase]
    {
        return [
            StringScoreTestCase(text: "hello world", searchString: "axl", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "hello world", searchString: "ow", fuzziness: nil, expectedScore: 0.354545454545455),
            StringScoreTestCase(text: "hello world", searchString: "e", fuzziness: nil, expectedScore: 0.109090909090909),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: nil, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "he", fuzziness: nil, expectedScore: 0.622727272727273),
            StringScoreTestCase(text: "hello world", searchString: "hel", fuzziness: nil, expectedScore: 0.659090909090909),
            StringScoreTestCase(text: "hello world", searchString: "hell", fuzziness: nil, expectedScore: 0.695454545454545),
            StringScoreTestCase(text: "hello world", searchString: "hello", fuzziness: nil, expectedScore: 0.731818181818182),
            StringScoreTestCase(text: "hello world", searchString: "hello worl", fuzziness: nil, expectedScore: 0.913636363636364),
            StringScoreTestCase(text: "hello world", searchString: "hello world", fuzziness: nil, expectedScore: 1.0),
            StringScoreTestCase(text: "hello world", searchString: "hello wor1", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: nil, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "H", fuzziness: nil, expectedScore: 0.531818181818182),
            StringScoreTestCase(text: "hello world", searchString: "HiMi", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "hello world", searchString: "Hills", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "hello world", searchString: "Hillsd", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "axl", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "ow", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "e", fuzziness: nil, expectedScore: 0.15),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: nil, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "he", fuzziness: nil, expectedScore: 0.9),
            StringScoreTestCase(text: "He", searchString: "hel", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "hell", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "hello", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "hello worl", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "hello world", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "hello wor1", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: nil, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "H", fuzziness: nil, expectedScore: 0.75),
            StringScoreTestCase(text: "He", searchString: "HiMi", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "Hills", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "Hillsd", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "axl", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "ow", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "e", fuzziness: nil, expectedScore: 0.12),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: nil, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "he", fuzziness: nil, expectedScore: 0.675),
            StringScoreTestCase(text: "Hello", searchString: "hel", fuzziness: nil, expectedScore: 0.763333333333333),
            StringScoreTestCase(text: "Hello", searchString: "hell", fuzziness: nil, expectedScore: 0.8475),
            StringScoreTestCase(text: "Hello", searchString: "hello", fuzziness: nil, expectedScore: 0.93),
            StringScoreTestCase(text: "Hello", searchString: "hello worl", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "hello world", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "hello wor1", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: nil, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "H", fuzziness: nil, expectedScore: 0.63),
            StringScoreTestCase(text: "Hello", searchString: "HiMi", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "Hills", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hello", searchString: "Hillsd", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "axl", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "ow", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "e", fuzziness: nil, expectedScore: 0.105555555555556),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: nil, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "he", fuzziness: nil, expectedScore: 0.4),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hel", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hell", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello worl", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello world", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello wor1", fuzziness: nil, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: nil, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "H", fuzziness: nil, expectedScore: 0.572222222222222),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "HiMi", fuzziness: nil, expectedScore: 0.669444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hills", fuzziness: nil, expectedScore: 0.661111111111111),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hillsd", fuzziness: nil, expectedScore: 0.683333333333333),
            StringScoreTestCase(text: "hello world", searchString: "axl", fuzziness: 0.5, expectedScore: 0.0212121212121212),
            StringScoreTestCase(text: "hello world", searchString: "ow", fuzziness: 0.5, expectedScore: 0.354545454545455),
            StringScoreTestCase(text: "hello world", searchString: "e", fuzziness: 0.5, expectedScore: 0.109090909090909),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: 0.5, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "he", fuzziness: 0.5, expectedScore: 0.622727272727273),
            StringScoreTestCase(text: "hello world", searchString: "hel", fuzziness: 0.5, expectedScore: 0.659090909090909),
            StringScoreTestCase(text: "hello world", searchString: "hell", fuzziness: 0.5, expectedScore: 0.695454545454545),
            StringScoreTestCase(text: "hello world", searchString: "hello", fuzziness: 0.5, expectedScore: 0.731818181818182),
            StringScoreTestCase(text: "hello world", searchString: "hello worl", fuzziness: 0.5, expectedScore: 0.913636363636364),
            StringScoreTestCase(text: "hello world", searchString: "hello world", fuzziness: 0.5, expectedScore: 1.0),
            StringScoreTestCase(text: "hello world", searchString: "hello wor1", fuzziness: 0.5, expectedScore: 0.608181818181818),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: 0.5, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "H", fuzziness: 0.5, expectedScore: 0.531818181818182),
            StringScoreTestCase(text: "hello world", searchString: "HiMi", fuzziness: 0.5, expectedScore: 0.197727272727273),
            StringScoreTestCase(text: "hello world", searchString: "Hills", fuzziness: 0.5, expectedScore: 0.273636363636364),
            StringScoreTestCase(text: "hello world", searchString: "Hillsd", fuzziness: 0.5, expectedScore: 0.272348484848485),
            StringScoreTestCase(text: "He", searchString: "axl", fuzziness: 0.5, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "ow", fuzziness: 0.5, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "e", fuzziness: 0.5, expectedScore: 0.15),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: 0.5, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "he", fuzziness: 0.5, expectedScore: 0.9),
            StringScoreTestCase(text: "He", searchString: "hel", fuzziness: 0.5, expectedScore: 0.566666666666667),
            StringScoreTestCase(text: "He", searchString: "hell", fuzziness: 0.5, expectedScore: 0.43125),
            StringScoreTestCase(text: "He", searchString: "hello", fuzziness: 0.5, expectedScore: 0.36),
            StringScoreTestCase(text: "He", searchString: "hello worl", fuzziness: 0.5, expectedScore: 0.24),
            StringScoreTestCase(text: "He", searchString: "hello world", fuzziness: 0.5, expectedScore: 0.230578512396694),
            StringScoreTestCase(text: "He", searchString: "hello wor1", fuzziness: 0.5, expectedScore: 0.24),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: 0.5, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "H", fuzziness: 0.5, expectedScore: 0.75),
            StringScoreTestCase(text: "He", searchString: "HiMi", fuzziness: 0.5, expectedScore: 0.27),
            StringScoreTestCase(text: "He", searchString: "Hills", fuzziness: 0.5, expectedScore: 0.243333333333333),
            StringScoreTestCase(text: "He", searchString: "Hillsd", fuzziness: 0.5, expectedScore: 0.226190476190476),
            StringScoreTestCase(text: "Hello", searchString: "axl", fuzziness: 0.5, expectedScore: 0.0266666666666667),
            StringScoreTestCase(text: "Hello", searchString: "ow", fuzziness: 0.5, expectedScore: 0.0466666666666667),
            StringScoreTestCase(text: "Hello", searchString: "e", fuzziness: 0.5, expectedScore: 0.12),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: 0.5, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "he", fuzziness: 0.5, expectedScore: 0.675),
            StringScoreTestCase(text: "Hello", searchString: "hel", fuzziness: 0.5, expectedScore: 0.763333333333333),
            StringScoreTestCase(text: "Hello", searchString: "hell", fuzziness: 0.5, expectedScore: 0.8475),
            StringScoreTestCase(text: "Hello", searchString: "hello", fuzziness: 0.5, expectedScore: 0.93),
            StringScoreTestCase(text: "Hello", searchString: "hello worl", fuzziness: 0.5, expectedScore: 0.317142857142857),
            StringScoreTestCase(text: "Hello", searchString: "hello world", fuzziness: 0.5, expectedScore: 0.291818181818182),
            StringScoreTestCase(text: "Hello", searchString: "hello wor1", fuzziness: 0.5, expectedScore: 0.317142857142857),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: 0.5, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "H", fuzziness: 0.5, expectedScore: 0.63),
            StringScoreTestCase(text: "Hello", searchString: "HiMi", fuzziness: 0.5, expectedScore: 0.222),
            StringScoreTestCase(text: "Hello", searchString: "Hills", fuzziness: 0.5, expectedScore: 0.33),
            StringScoreTestCase(text: "Hello", searchString: "Hillsd", fuzziness: 0.5, expectedScore: 0.282),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "axl", fuzziness: 0.5, expectedScore: 0.12962962962963),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "ow", fuzziness: 0.5, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "e", fuzziness: 0.5, expectedScore: 0.105555555555556),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: 0.5, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "he", fuzziness: 0.5, expectedScore: 0.4),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hel", fuzziness: 0.5, expectedScore: 0.266666666666667),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hell", fuzziness: 0.5, expectedScore: 0.21875),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello", fuzziness: 0.5, expectedScore: 0.196),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello worl", fuzziness: 0.5, expectedScore: 0.179382716049383),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello world", fuzziness: 0.5, expectedScore: 0.17489898989899),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello wor1", fuzziness: 0.5, expectedScore: 0.179382716049383),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: 0.5, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "H", fuzziness: 0.5, expectedScore: 0.572222222222222),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "HiMi", fuzziness: 0.5, expectedScore: 0.669444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hills", fuzziness: 0.5, expectedScore: 0.661111111111111),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hillsd", fuzziness: 0.5, expectedScore: 0.683333333333333),
            StringScoreTestCase(text: "hello world", searchString: "axl", fuzziness: 0.7, expectedScore: 0.0265151515151515),
            StringScoreTestCase(text: "hello world", searchString: "ow", fuzziness: 0.7, expectedScore: 0.354545454545455),
            StringScoreTestCase(text: "hello world", searchString: "e", fuzziness: 0.7, expectedScore: 0.109090909090909),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: 0.7, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "he", fuzziness: 0.7, expectedScore: 0.622727272727273),
            StringScoreTestCase(text: "hello world", searchString: "hel", fuzziness: 0.7, expectedScore: 0.659090909090909),
            StringScoreTestCase(text: "hello world", searchString: "hell", fuzziness: 0.7, expectedScore: 0.695454545454545),
            StringScoreTestCase(text: "hello world", searchString: "hello", fuzziness: 0.7, expectedScore: 0.731818181818182),
            StringScoreTestCase(text: "hello world", searchString: "hello worl", fuzziness: 0.7, expectedScore: 0.913636363636364),
            StringScoreTestCase(text: "hello world", searchString: "hello world", fuzziness: 0.7, expectedScore: 1.0),
            StringScoreTestCase(text: "hello world", searchString: "hello wor1", fuzziness: 0.7, expectedScore: 0.678671328671329),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: 0.7, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "H", fuzziness: 0.7, expectedScore: 0.531818181818182),
            StringScoreTestCase(text: "hello world", searchString: "HiMi", fuzziness: 0.7, expectedScore: 0.212799043062201),
            StringScoreTestCase(text: "hello world", searchString: "Hills", fuzziness: 0.7, expectedScore: 0.304545454545455),
            StringScoreTestCase(text: "hello world", searchString: "Hillsd", fuzziness: 0.7, expectedScore: 0.302935606060606),
            StringScoreTestCase(text: "He", searchString: "axl", fuzziness: 0.7, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "ow", fuzziness: 0.7, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "e", fuzziness: 0.7, expectedScore: 0.15),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: 0.7, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "he", fuzziness: 0.7, expectedScore: 0.9),
            StringScoreTestCase(text: "He", searchString: "hel", fuzziness: 0.7, expectedScore: 0.630769230769231),
            StringScoreTestCase(text: "He", searchString: "hell", fuzziness: 0.7, expectedScore: 0.5015625),
            StringScoreTestCase(text: "He", searchString: "hello", fuzziness: 0.7, expectedScore: 0.426315789473684),
            StringScoreTestCase(text: "He", searchString: "hello worl", fuzziness: 0.7, expectedScore: 0.282352941176471),
            StringScoreTestCase(text: "He", searchString: "hello world", fuzziness: 0.7, expectedScore: 0.26977886977887),
            StringScoreTestCase(text: "He", searchString: "hello wor1", fuzziness: 0.7, expectedScore: 0.282352941176471),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: 0.7, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "H", fuzziness: 0.7, expectedScore: 0.75),
            StringScoreTestCase(text: "He", searchString: "HiMi", fuzziness: 0.7, expectedScore: 0.307894736842105),
            StringScoreTestCase(text: "He", searchString: "Hills", fuzziness: 0.7, expectedScore: 0.277272727272727),
            StringScoreTestCase(text: "He", searchString: "Hillsd", fuzziness: 0.7, expectedScore: 0.256666666666667),
            StringScoreTestCase(text: "Hello", searchString: "axl", fuzziness: 0.7, expectedScore: 0.0333333333333333),
            StringScoreTestCase(text: "Hello", searchString: "ow", fuzziness: 0.7, expectedScore: 0.0538461538461538),
            StringScoreTestCase(text: "Hello", searchString: "e", fuzziness: 0.7, expectedScore: 0.12),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: 0.7, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "he", fuzziness: 0.7, expectedScore: 0.675),
            StringScoreTestCase(text: "Hello", searchString: "hel", fuzziness: 0.7, expectedScore: 0.763333333333333),
            StringScoreTestCase(text: "Hello", searchString: "hell", fuzziness: 0.7, expectedScore: 0.8475),
            StringScoreTestCase(text: "Hello", searchString: "hello", fuzziness: 0.7, expectedScore: 0.93),
            StringScoreTestCase(text: "Hello", searchString: "hello worl", fuzziness: 0.7, expectedScore: 0.384),
            StringScoreTestCase(text: "Hello", searchString: "hello world", fuzziness: 0.7, expectedScore: 0.352597402597403),
            StringScoreTestCase(text: "Hello", searchString: "hello wor1", fuzziness: 0.7, expectedScore: 0.384),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: 0.7, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "H", fuzziness: 0.7, expectedScore: 0.63),
            StringScoreTestCase(text: "Hello", searchString: "HiMi", fuzziness: 0.7, expectedScore: 0.244736842105263),
            StringScoreTestCase(text: "Hello", searchString: "Hills", fuzziness: 0.7, expectedScore: 0.375),
            StringScoreTestCase(text: "Hello", searchString: "Hillsd", fuzziness: 0.7, expectedScore: 0.323684210526316),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "axl", fuzziness: 0.7, expectedScore: 0.14957264957265),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "ow", fuzziness: 0.7, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "e", fuzziness: 0.7, expectedScore: 0.105555555555556),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: 0.7, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "he", fuzziness: 0.7, expectedScore: 0.4),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hel", fuzziness: 0.7, expectedScore: 0.284615384615385),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hell", fuzziness: 0.7, expectedScore: 0.2359375),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello", fuzziness: 0.7, expectedScore: 0.210526315789474),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello worl", fuzziness: 0.7, expectedScore: 0.192652329749104),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello world", fuzziness: 0.7, expectedScore: 0.186616161616162),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello wor1", fuzziness: 0.7, expectedScore: 0.192652329749104),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: 0.7, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "H", fuzziness: 0.7, expectedScore: 0.572222222222222),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "HiMi", fuzziness: 0.7, expectedScore: 0.669444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hills", fuzziness: 0.7, expectedScore: 0.661111111111111),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hillsd", fuzziness: 0.7, expectedScore: 0.683333333333333),
            StringScoreTestCase(text: "hello world", searchString: "axl", fuzziness: 1.0, expectedScore: 0.0424242424242424),
            StringScoreTestCase(text: "hello world", searchString: "ow", fuzziness: 1.0, expectedScore: 0.354545454545455),
            StringScoreTestCase(text: "hello world", searchString: "e", fuzziness: 1.0, expectedScore: 0.109090909090909),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: 1.0, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "he", fuzziness: 1.0, expectedScore: 0.622727272727273),
            StringScoreTestCase(text: "hello world", searchString: "hel", fuzziness: 1.0, expectedScore: 0.659090909090909),
            StringScoreTestCase(text: "hello world", searchString: "hell", fuzziness: 1.0, expectedScore: 0.695454545454545),
            StringScoreTestCase(text: "hello world", searchString: "hello", fuzziness: 1.0, expectedScore: 0.731818181818182),
            StringScoreTestCase(text: "hello world", searchString: "hello worl", fuzziness: 1.0, expectedScore: 0.913636363636364),
            StringScoreTestCase(text: "hello world", searchString: "hello world", fuzziness: 1.0, expectedScore: 1.0),
            StringScoreTestCase(text: "hello world", searchString: "hello wor1", fuzziness: 1.0, expectedScore: 0.837272727272727),
            StringScoreTestCase(text: "hello world", searchString: "h", fuzziness: 1.0, expectedScore: 0.586363636363636),
            StringScoreTestCase(text: "hello world", searchString: "H", fuzziness: 1.0, expectedScore: 0.531818181818182),
            StringScoreTestCase(text: "hello world", searchString: "HiMi", fuzziness: 1.0, expectedScore: 0.269318181818182),
            StringScoreTestCase(text: "hello world", searchString: "Hills", fuzziness: 1.0, expectedScore: 0.397272727272727),
            StringScoreTestCase(text: "hello world", searchString: "Hillsd", fuzziness: 1.0, expectedScore: 0.39469696969697),
            StringScoreTestCase(text: "He", searchString: "axl", fuzziness: 1.0, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "ow", fuzziness: 1.0, expectedScore: 0.0),
            StringScoreTestCase(text: "He", searchString: "e", fuzziness: 1.0, expectedScore: 0.15),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: 1.0, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "he", fuzziness: 1.0, expectedScore: 0.9),
            StringScoreTestCase(text: "He", searchString: "hel", fuzziness: 1.0, expectedScore: 0.775),
            StringScoreTestCase(text: "He", searchString: "hell", fuzziness: 1.0, expectedScore: 0.7125),
            StringScoreTestCase(text: "He", searchString: "hello", fuzziness: 1.0, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "hello worl", fuzziness: 1.0, expectedScore: 0.6),
            StringScoreTestCase(text: "He", searchString: "hello world", fuzziness: 1.0, expectedScore: 0.593181818181818),
            StringScoreTestCase(text: "He", searchString: "hello wor1", fuzziness: 1.0, expectedScore: 0.6),
            StringScoreTestCase(text: "He", searchString: "h", fuzziness: 1.0, expectedScore: 0.675),
            StringScoreTestCase(text: "He", searchString: "H", fuzziness: 1.0, expectedScore: 0.75),
            StringScoreTestCase(text: "He", searchString: "HiMi", fuzziness: 1.0, expectedScore: 0.45),
            StringScoreTestCase(text: "He", searchString: "Hills", fuzziness: 1.0, expectedScore: 0.43),
            StringScoreTestCase(text: "He", searchString: "Hillsd", fuzziness: 1.0, expectedScore: 0.416666666666667),
            StringScoreTestCase(text: "Hello", searchString: "axl", fuzziness: 1.0, expectedScore: 0.0533333333333333),
            StringScoreTestCase(text: "Hello", searchString: "ow", fuzziness: 1.0, expectedScore: 0.07),
            StringScoreTestCase(text: "Hello", searchString: "e", fuzziness: 1.0, expectedScore: 0.12),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: 1.0, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "he", fuzziness: 1.0, expectedScore: 0.675),
            StringScoreTestCase(text: "Hello", searchString: "hel", fuzziness: 1.0, expectedScore: 0.763333333333333),
            StringScoreTestCase(text: "Hello", searchString: "hell", fuzziness: 1.0, expectedScore: 0.8475),
            StringScoreTestCase(text: "Hello", searchString: "hello", fuzziness: 1.0, expectedScore: 0.93),
            StringScoreTestCase(text: "Hello", searchString: "hello worl", fuzziness: 1.0, expectedScore: 0.735),
            StringScoreTestCase(text: "Hello", searchString: "hello world", fuzziness: 1.0, expectedScore: 0.717272727272727),
            StringScoreTestCase(text: "Hello", searchString: "hello wor1", fuzziness: 1.0, expectedScore: 0.735),
            StringScoreTestCase(text: "Hello", searchString: "h", fuzziness: 1.0, expectedScore: 0.57),
            StringScoreTestCase(text: "Hello", searchString: "H", fuzziness: 1.0, expectedScore: 0.63),
            StringScoreTestCase(text: "Hello", searchString: "HiMi", fuzziness: 1.0, expectedScore: 0.33),
            StringScoreTestCase(text: "Hello", searchString: "Hills", fuzziness: 1.0, expectedScore: 0.51),
            StringScoreTestCase(text: "Hello", searchString: "Hillsd", fuzziness: 1.0, expectedScore: 0.48),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "axl", fuzziness: 1.0, expectedScore: 0.194444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "ow", fuzziness: 1.0, expectedScore: 0.0),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "e", fuzziness: 1.0, expectedScore: 0.105555555555556),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: 1.0, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "he", fuzziness: 1.0, expectedScore: 0.4),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hel", fuzziness: 1.0, expectedScore: 0.325),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hell", fuzziness: 1.0, expectedScore: 0.2875),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello", fuzziness: 1.0, expectedScore: 0.265),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello worl", fuzziness: 1.0, expectedScore: 0.282222222222222),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello world", fuzziness: 1.0, expectedScore: 0.274494949494949),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "hello wor1", fuzziness: 1.0, expectedScore: 0.282222222222222),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "h", fuzziness: 1.0, expectedScore: 0.519444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "H", fuzziness: 1.0, expectedScore: 0.572222222222222),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "HiMi", fuzziness: 1.0, expectedScore: 0.669444444444444),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hills", fuzziness: 1.0, expectedScore: 0.661111111111111),
            StringScoreTestCase(text: "Hillsdale Michigan", searchString: "Hillsd", fuzziness: 1.0, expectedScore: 0.683333333333333),
        ]
    }
}
