source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StringScoreDemo', :exclusive => true do
  pod 'StringScore_Swift', :path => '../'
end

target 'StringScoreTests', :exclusive => true do
  pod 'StringScore_Swift', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
