source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StringScoreDemo', :exclusive => true do
 # pod 'StringScore_Swift', :path => '../'
end

target 'StringScoreDemoTests', :exclusive => true do
 # pod 'StringScore_Swift', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
